### ISSUE TITLE
create user dataset in js file

### ISSUE THREAD

**Issue by cnfairall** [nss-evening-cohort-24/gitsub-team-6#11]
# User Story
All pages will utilize the same dataset stored in a javascript file/folder and render that data differently according to its individual functions.

# Acceptance Criteria
All four pages (Overview, Projects, Repos, Packages) should be able to display the same user data.
Data should include user:
profile: image
name
username
bio
followers/following/stars
location
email
website
twitter
highlights array
organizations array
sponsors array

repos (at least 5) (array)
project array
package array
pin array
repo: name, description, tags, language, stars, branches, issues, last update
project: name, date, description, private boolean
package: name, blurb
pin: name, blurb, language, stars, branches

# Dependencies
we need to figure out how to import separate files into other files in order to access this data.

**Comment by JohnnySaniat** [comment]
Created a complex data set to utilize on our pages
