### ISSUE TITLE
Write utility functions

### ISSUE THREAD

**Issue by cnfairall** [nss-evening-cohort-24/gitsub-team-6#13]
# User Story
renderToDom: for each html container render content dynamically
"cardsOnDom": render content cards in correct containers
addNewObject: use form to add new object, push to correct array, render array to container
delete pin

# Acceptance Criteria
WHEN the user visits any page, html content renders in content containers
When user submits a form, they create a new object (repo, pin, project, package)
Then object is pushed to corresponding array
Then that array is re-rendered to the page to reflect the change

# Dependencies
write functions and decide parameters
decide arguments that will specify what content is loaded depending on the page

**Comment by JohnnySaniat** [comment]
Coded the utility functions and broke them out for each array of data
