### ISSUE TITLE
Divide Responsibilities

### ISSUE THREAD

**Issue by JohnnySaniat** [nss-evening-cohort-24/gitsub-team-6#15]
Breakout the tasks in each phase of the project into bite size pieces so that they are easily branched and manageable to ensure smooth interconnectivity

**Comment by cnfairall** [comment]
as a group: index, utility functions
css:
proj.js:
pins.js:
package:
repo:
header/footer:
profile:

**Comment by JohnnySaniat** [comment]
Talked through the responsibilities and began to talk through the code when the group gave guidance
