### ISSUE TITLE
create html template for all pages

### ISSUE THREAD

**Issue by cnfairall** [nss-evening-cohort-24/gitsub-team-6#4]
# User Story
Create framework in html document to contain our content.

# Acceptance Criteria
The template will contain 5 containers: nav bar, footer, profile, a form container, and a box for content specific to the page.
Content within the containers will be rendered dynamically.

We will use bootstrap components for cards, form, buttons, etc.

# Dependencies
-create index.html
-create head, body
-link scripts and styling
-integrate bootstrap links
-create divs for each container and to separate page elements

**Comment by GitEbachS** [comment]
We created four index.html pages:
index.html
repos.html
projects.html
packages.html
